name: Build and Test

on:
  push:
    paths:
      - 'src/**'
      - 'build/**'
  pull_request:
    paths:
      - 'src/**'
      - 'build/**'
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test on ${{ matrix.os }}
    # https://github.community/t/duplicate-checks-on-push-and-pull-request-simultaneous-event/18012/5
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            installDir: /usr/share/dotnet
          - os: windows-latest
            installDir: C:\Program Files\dotnet
          - os: macos-latest
            installDir: /Users/runner/.dotnet
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.1.x
            6.0.x
            7.0.x
          include-prerelease: True
        env:
          DOTNET_INSTALL_DIR: ${{ matrix.installDir }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run Tests
        run: dotnet test --no-build -- xunit.parallelizeAssembly=true xunit.parallelizeTestCollections=true xunit.maxParallelThreads=-1
