# Docs build script based on https://tehgm.net/blog/docfx-github-actions/
name: DocFX Build and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.1.x
            6.0.x
          include-prerelease: True
        env:
          DOTNET_INSTALL_DIR: C:\Program Files\dotnet

      - name: Setup DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx

      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: DocFX Build
        working-directory: docs
        run: docfx docfx.json
        continue-on-error: false

      - name: Copy static assets
        run: |
          Get-ChildItem -Recurse -Name ./docs/static/ | ForEach-Item {
            Move-Item -Path "./docs/static/$_" "./docs/_site/$_";
          }

      - name: Publish
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: cf-pages
          publish_dir: docs/_site
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "${{ github.event.head_commit.message }}"
